# Consume
USER_CREATED_TOPIC = "employee.created"
EMPLOYEE_UPDATED_TOPIC = "employee.updated"
EMPLOYEE_PROFILE_CREATED_TOPIC = "employee.profile_created"
EMPLOYEE_ROLE_ASSIGNED_TOPIC = "employee.role_assigned"
EMPLOYEE_PROJECT_ASSIGNED_TOPIC = "employee.project_assigned"
PROJECT_CREATED_TOPIC = "project.created"
PROJECT_UPDATED_TOPIC = "project.updated"
PROJECT_DELETED_TOPIC = "project.deleted"
PROJECT_ROLE_CREATED_TOPIC = "project_role.created"
PROJECT_ROLE_UPDATED_TOPIC = "project_role.updated"
PROJECT_ROLE_DELETED_TOPIC = "project_role.deleted"
ROLE_CREATED_TOPIC = "role.created"
ROLE_UPDATED_TOPIC = "role.updated"
ROLE_DELETED_TOPIC = "role.deleted"
ABSENCE_STATUS_CHANGED_TOPIC = "absence.status_changed"

# Publish
OVERTIME_CREATED_TOPIC = "timesheet.overtime_created"
ENTRY_CREATED_TOPIC = "timesheet.entry_created"
ENTRY_UPDATED_TOPIC = "timesheet.entry_updated"
ENTRY_DELETED_TOPIC = "timesheet.entry_deleted"
PERIOD_SUBMITTED_TOPIC = "timesheet.period_submitted"
PERIOD_APPROVED_TOPIC = "timesheet.period_approved"
PERIOD_REJECTED_TOPIC = "timesheet.period_rejected"
